"use client";
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9cdhoavYn4e
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { NavigationMenu, NavigationMenuList, NavigationMenuLink } from "@/components/ui/navigation-menu"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import Image from 'next/image';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { ModeToggle } from "../theme-toggle";
import { use } from "react";
import { useTheme } from "next-themes";

const pages = [
  //'Domů', 'QR Oprava'
  {
    name: 'Domů',
    link: '/'
  },
  {
    name: "Vyhledávání",
    link: "/lookup"
  },
  {
    name: 'Celkové statistiky',
    link: '/charts'
  },
  {
    name: 'Replay',
    link: '/replay'
  },
  {
    name: 'Github',
    link: 'https://github.com/Molenusaczech/CerveneKombo'
  }
];

const depracedPages = [
  {
    name: 'QR Oprava',
    link: '/qr'
  },
  {
    name: 'Editor',
    link: '/edit'
  },
]

export function NavBar() {
  "use client;"
  return (
    <header className="flex h-16 w-full shrink-0 items-center px-4 md:px-6 bg-red-500 dark:bg-red-950 text-white">
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon" className="lg:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left">
          <nav className="grid gap-2 py-6">
            {pages.map((curPage, index) => {
              return (
                <Link href={curPage.link} key={index} className="flex w-full items-center py-2 text-lg font-semibold" prefetch={false}>
                  {curPage.name}
                </Link>
              )
            })}
            <DropdownMenu>
              <DropdownMenuTrigger
                className="flex w-full items-center py-2 text-lg font-semibold"
              >
                Zastaralé nástroje
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                {depracedPages.map((page, index) => {
                  return (
                    <DropdownMenuItem key={index}>
                      <Link href={page.link} className="flex w-full items-center py-2 text-lg font-semibold" prefetch={false}>
                        {page.name}
                      </Link>
                    </DropdownMenuItem>)
                })}
              </DropdownMenuContent>
            </DropdownMenu>
            <ModeToggle />
          </nav>
        </SheetContent>
      </Sheet>
      <Link href="/" className="mr-6 flex items-center gap-2 text-lg font-semibold text-white" prefetch={false}>
        <Image src="/combo.png" alt="Kombo" width={40} height={36} className='pr-1' />
        <span>Červené kombo</span>
      </Link>
      <NavigationMenu className="hidden lg:flex">
        <NavigationMenuList>
          {pages.map((curPage, index) => {
            return (<NavigationMenuLink asChild key={index}>
              <Link
                href={curPage.link}
                className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-red-500 px-4 py-2 text-sm font-medium transition-colors hover:bg-red-600 focus:bg-red-600 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-red-600 text-white dark:bg-red-950"
                prefetch={false}
              >
                {curPage.name}
              </Link>
            </NavigationMenuLink>)
          })}

          <DropdownMenu>
            <DropdownMenuTrigger
              className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-red-500 px-4 py-2 text-sm font-medium transition-colors hover:bg-red-600 focus:bg-red-600 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-red-600 text-white dark:bg-red-950"
            >
              Zastaralé nástroje
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              {depracedPages.map((page, index) => {
                return (
                  <DropdownMenuItem key={index}>
                    <NavigationMenuLink>
                      <Link href={page.link} className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-red-500 px-4 py-2 text-sm font-medium transition-colors hover:bg-red-600 focus:bg-red-600 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-red-600 text-white" prefetch={false}>
                        {page.name}
                      </Link>
                    </NavigationMenuLink>
                  </DropdownMenuItem>)
              })}
            </DropdownMenuContent>
          </DropdownMenu>
          <div className="self-end">
            <ModeToggle />
          </div>
        </NavigationMenuList>
      </NavigationMenu>
    </header>
  )
}

function MenuIcon(props: any) {

  const { theme, setTheme } = useTheme();

  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke={theme === 'dark' ? 'white' : 'black'}
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
