type effectType = "ENERGY" |
"HERO_ATTACK" |
"WEAPON_ATTACK" |
"UNIVERSAL_ATTACK" |
"HEAL" |
"PERMANENT_ATTACK" |
"DEFENSE" |
"COMBO" |
"BLESS" |
"COMBO_DETONATOR" |
"OBLITERATE" |
"BATTLE_TRICK" |
"VAMPIRE_BITE" |
"CURSE_WEAPON" |
"NIGHT_ATTACK" |
"MECHANICS_SUPERACTION" |
"TRAP" |
"ZEPPLANDIAN_SHRAPNEL" |
"ZEPPLANDIAN_SHRAPNEL_2" |
"CUMULUS" |
"EXTRA_COINS"

export type { effectType }